### ISSUE TITLE
Trouble with SDK Honoring Promises

### ISSUE THREAD

**Issue by rcldesign** [Bandwidth/node-bandwidth#131]
It's not covered in the documentation, but when I receive a callback from Bandwidth (e.g. from an incoming call), how am I supposed to respond to that callback? I'm assuming that I should just make REST calls instead of responding with some kind of string (likeI would with Twilio),   ##but I'm having all kinds of issues:

1. Tried using SDK to can REST interface with callId to do something basic, like answer, then speak sentence, then hangup. It seems like the SDK was not honoring promises and instead just skipped over the subsequent .then() statements.

2. Tried to create some BXML and send it back as a response. That didn't do anything.

3. Gave up with all of that, and just decided to use the SDK to fire off an SMS when the callback is hit. This is having the same issue as #1 where it jut skips over the .then() statements. Below is my code and output... what am I doing wrong here?

`'use strict';

const Bandwidth = require('node-bandwidth');

exports.handle = function (event, context, callback) {

    console.log('Received event: ', JSON.stringify(event, null, 2));
    console.log('Received context: ', JSON.stringify(context, null, 2));

    if(event.eventType === 'incomingcall') {
        let client = new Bandwidth({
            userId: 'u---------------------------',
            apiToken: 't--------------------------',
            apiSecret: '---------------------------'
        });

        console.log('Pre');
        client.Message.send({
            from: '+1----------',
            to: '+1----------',
            text: 'This is a test message'
        })
        .then(message => {
            console.log('sent a message: ' + message);
        })
        .catch(err => {
            console.log('error: ' + err.message);
        })
        .finally(() => {
            console.log('hit the finally block');
            return context.succeed();
        });

        console.log('how did I get here?');
    }
    else {
        console.log('Incoming connection was not an incoming call');
        return context.succeed();
    }   
}`

Output:
... after the event and context objects are spit out on the console...
Pre
how did I get here?

... and no message was sent
... probably not an *issue*, but I can't find anywhere else to get support for the SDK...

**Comment by dtolb** [comment]
## Bandwidth REST API & Async
Bandwidth has two different options for responding to callbacks. When your [`callbackHttpMethod`](http://dev.bandwidth.com/ap-docs/methods/applications/postApplications.html) is set to `POST`, _everything_ is handled asyncronously, so only the status code of the response is checked at Bandwidth's servers.  So, really, you immediately respond to the callback with something like `res.send(200)`.

## Bandwidth BXML
However, if you have your [`callbackHttpMethod`](http://dev.bandwidth.com/ap-docs/methods/applications/postApplications.html) set to `GET` **AND** `autoAnswer: true` in the application. You **CAN** respond to the callback with BXML and it functions _mostly_ like TWilio.  BXML is currently only supported for calls.  We're working to improve this somewhat fragmented experience but for now this is how to handle it.

## Your Example
I'm not entirely sure what framework you're working on, but i took a stab at filling out your answer call and speak sentence example for both the ASYNC mode and BXML.
Note that I changed the exports to `handlePost` and `handleGet`. And for the BXML sample, the callback information is contained in the query parameters which I guessed would be at `event.query`

This assumes you have [`autoAnswer`](http://dev.bandwidth.com/ap-docs/methods/applications/postApplications.html) set to `False`.
If you have `autoAnswer` set to true, you will receive the `incomingcall` event and then the `answer` event **IMMEDIATELY** and the function `call.answer` will fail because the call state will already be active. If that's the case, just comment out the `answer` code and proceed to `event.eventType === 'answer'`

### Code:

```js
'use strict';

const Bandwidth = require('node-bandwidth');

/* For POST! */
exports.handlePost = function (event, context, callback) {

    console.log('Received event: ', JSON.stringify(event, null, 2));
    console.log('Received context: ', JSON.stringify(context, null, 2));

    // Go ahead and succeed here
    context.succeed();
    let client = new Bandwidth({
        userId: 'u---------------------------',
        apiToken: 't--------------------------',
        apiSecret: '---------------------------'
    });

    if(event.eventType === 'incomingcall') {
        client.Call.answer(event.callId)
        .then( res => {
            console.log('Answered Call');
        })
        .catch( err => {
            console.log('Error answering the call')
            console.log(err);
        });
    }
    else if(event.eventType === 'answer') {
        client.Call.speakSentence(event.callId, 'Hello From Bandwidth!!!');
        .then( res => {
            console.log('Speaking on Call');
            console.log(res);
        })
        .catch( err => {
            console.log('Error Speaking on call');
            console.log(err);
        });
    }
    else if(event.eventType === 'speak' && event.status === 'started') {
        console.log('Started speak playback');
    }
    else if(event.eventType === 'speak' && event.status === 'done') {
        console.log('Finished speak playback');
        client.Call.hangup(event.callId)
        .then( res => {
            console.log('Hungup call!');
            console.log(res);
        })
        .catch( err => {
            console.log('Error hanging up the call');
            console.log(err);
        });
    }
    else if(event.eventType === 'hangup') {
        console.log('Call hangup!');
    }
    else {
        console.log('Incoming connection was not an incoming call');
    }

    return;
}

const bxml = `<?xml version="1.0" encoding="UTF-8"?>

<Response>

<SpeakSentence gender="female">
Hello from Bandwidth
</SpeakSentence>
<Hangup></Hangup>

</Response>`

/* Handle BXML REQUEST */
exports.handleGet = function (event, context, callback) {

    console.log('Received event: ', JSON.stringify(event, null, 2));
    console.log('Received context: ', JSON.stringify(context, null, 2));

    if(event.query.eventType === 'incomingcall') {
        console.log('Ignore Autoanswer');
        return context.succeed();
    }

    else if(event.eventType === 'answer') {
        console.log('ANSWERED CALL');
        return context.succeed(bxml);

    }
}
```

**Comment by dtolb** [comment]
@rcldesign going to close for now. let us know if you need further help.

-DT
